// <auto-generated />
using System;
using MarriageCalculator.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarriageCalculator.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221009232802_fixforeignkey")]
    partial class fixforeignkey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("MarriageCalculator.Core.Models.MarriageGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MarriageGame");
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MarriageGameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MarriageGameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.Player", b =>
                {
                    b.HasOne("MarriageCalculator.Core.Models.MarriageGame", null)
                        .WithMany("Players")
                        .HasForeignKey("MarriageGameId");
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.MarriageGame", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
