// <auto-generated />
using System;
using MarriageCalculator.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarriageCalculator.API.Migrations
{
    [DbContext(typeof(MarriageCalculatorDbContext))]
    partial class MarriageCalculatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarriageCalculator.Core.Models.GameSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Audio")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<bool>("Dublee")
                        .HasColumnType("bit");

                    b.Property<int>("DubleePointBonus")
                        .HasColumnType("int");

                    b.Property<bool>("DubleePointLess")
                        .HasColumnType("bit");

                    b.Property<int>("FoulPoint")
                        .HasColumnType("int");

                    b.Property<int>("FoulPointBonus")
                        .HasColumnType("int");

                    b.Property<bool>("Kidnap")
                        .HasColumnType("bit");

                    b.Property<bool>("Murder")
                        .HasColumnType("bit");

                    b.Property<double>("PointRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<int>("SeenPoint")
                        .HasColumnType("int");

                    b.Property<int>("UnseenPoint")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GameSettings", (string)null);
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.MarriageGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ClosedRound")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MarriageGameRoundId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("TotalMaal")
                        .HasColumnType("int");

                    b.Property<Guid>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("MarriageGameRoundId");

                    b.HasIndex("WinnerId");

                    b.ToTable("MarriageGame", (string)null);
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.MarriageGameRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<int>("MarriageGameSetId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarriageGameSetId");

                    b.ToTable("MarriageGameRound", (string)null);
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.MarriageGameScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusPoint")
                        .HasColumnType("int")
                        .HasColumnName("BonusPoint");

                    b.Property<bool>("Deal")
                        .HasColumnType("bit")
                        .HasColumnName("Deal");

                    b.Property<bool>("Duply")
                        .HasColumnType("bit")
                        .HasColumnName("Duply");

                    b.Property<int>("Maal")
                        .HasColumnType("int")
                        .HasColumnName("Maal");

                    b.Property<int>("MarriageGameId")
                        .HasColumnType("int");

                    b.Property<double>("MoneyWon")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)")
                        .HasColumnName("MoneyWon");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Playing")
                        .HasColumnType("bit")
                        .HasColumnName("Playing");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("Position");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("Score");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit")
                        .HasColumnName("Seen");

                    b.Property<bool>("Winner")
                        .HasColumnType("bit")
                        .HasColumnName("Winner");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MarriageGameId", "PlayerId")
                        .IsUnique();

                    b.ToTable("MarriageGameScore", (string)null);
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.MarriageGameSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("GameSettingsId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GameSettingsId");

                    b.ToTable("MarriageGameSet", (string)null);
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.MarriageGameSetPlayer", b =>
                {
                    b.Property<int>("MarriageGameSetId")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MarriageGameSetId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MarriageGameSetPlayer", (string)null);
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedByUserId");

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Deleted");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<bool>("Selected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Selected");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name", "Email")
                        .IsUnique();

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiresAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ReplacedByToken");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("RevokedAt");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RevokedReason");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("IsEmailVerified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastLoginAt");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Salt");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.UserEmailVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiresAt");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("IsUsed");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UsedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("VerificationCode");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "VerificationCode", "IsUsed");

                    b.ToTable("UserEmailVerification", (string)null);
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.GameSettings", b =>
                {
                    b.HasOne("MarriageCalculator.Core.Models.User", "User")
                        .WithMany("GameSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.MarriageGame", b =>
                {
                    b.HasOne("MarriageCalculator.Core.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarriageCalculator.Core.Models.MarriageGameRound", null)
                        .WithMany()
                        .HasForeignKey("MarriageGameRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarriageCalculator.Core.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.MarriageGameRound", b =>
                {
                    b.HasOne("MarriageCalculator.Core.Models.MarriageGameSet", null)
                        .WithMany()
                        .HasForeignKey("MarriageGameSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.MarriageGameScore", b =>
                {
                    b.HasOne("MarriageCalculator.Core.Models.MarriageGame", null)
                        .WithMany()
                        .HasForeignKey("MarriageGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarriageCalculator.Core.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.MarriageGameSet", b =>
                {
                    b.HasOne("MarriageCalculator.Core.Models.GameSettings", null)
                        .WithMany()
                        .HasForeignKey("GameSettingsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.MarriageGameSetPlayer", b =>
                {
                    b.HasOne("MarriageCalculator.Core.Models.MarriageGameSet", "MarriageGameSet")
                        .WithMany()
                        .HasForeignKey("MarriageGameSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarriageCalculator.Core.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarriageGameSet");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.Player", b =>
                {
                    b.HasOne("MarriageCalculator.Core.Models.User", "CreatedByUser")
                        .WithMany("CreatedPlayers")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.RefreshToken", b =>
                {
                    b.HasOne("MarriageCalculator.Core.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.UserEmailVerification", b =>
                {
                    b.HasOne("MarriageCalculator.Core.Models.User", "User")
                        .WithMany("EmailVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarriageCalculator.Core.Models.User", b =>
                {
                    b.Navigation("CreatedPlayers");

                    b.Navigation("EmailVerifications");

                    b.Navigation("GameSettings");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
